name: user_repository
description: The repo which handle users.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
